apiVersion: v1
kind: Secret
metadata:
  name: ormconfig-env
type: Opaque
data:
  ormconfig.env: VFlQRU9STV9DT05ORUNUSU9OID0gbXlzcWwKVFlQRU9STV9IT1NUID0gbWFyaWFkYgpUWVBFT1JNX1BPUlQgPSAzMzA2ClRZUEVPUk1fVVNFUk5BTUUgPSB0ZXN0ClRZUEVPUk1fUEFTU1dPUkQgPSB0ZXN0ClRZUEVPUk1fREFUQUJBU0UgPSB0ZXN0ClRZUEVPUk1fU1lOQ0hST05JWkUgPSB0cnVlClRZUEVPUk1fRU5USVRJRVMgPSBzcmMvZW50aXR5LyouanMKVFlQRU9STV9TVUJTQ1JJQkVSUyA9IHNyYy9zdWJzY3JpYmVyLyouanMKVFlQRU9STV9NSUdSQVRJT05TID0gc3JjL21pZ3JhdGlvbi8qLmpzClRZUEVPUk1fRU5USVRJRVNfRElSID0gc3JjL2VudGl0eQpUWVBFT1JNX01JR1JBVElPTlNfRElSID0gc3JjL21pZ3JhdGlvbgpUWVBFT1JNX1NVQlNDUklCRVJTX0RJUiA9IHNyYy9zdWJzY3JpYmVy
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJpaHNycCIsInBhc3N3b3JkIjoiYWRQJFZUSm9cdTAwMjZland3czkhSyUjdFhQSkpUTEhSQXdpaXd6KnZqVXpLdVx1MDAyNm9ndWpybzRMYU5jblZtTkJLRSIsImVtYWlsIjoiaWhzcnBAY2luLnVmcGUuYnIiLCJhdXRoIjoiYVdoemNuQTZZV1JRSkZaVVNtOG1aV3AzZDNNNUlVc2xJM1JZVUVwS1ZFeElVa0YzYVdsM2VpcDJhbFY2UzNVbWIyZDFhbkp2TkV4aFRtTnVWbTFPUWt0RiJ9fX0=